[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/jobs*"
  to = "/.netlify/functions/jobs"
  status = 200

[[redirects]]
  from = "/api/photo*"
  to = "/.netlify/functions/photo"
  status = 200

[[redirects]]
  from = "/api/report*"
  to = "/.netlify/functions/report"
  status = 200

[[redirects]]
  from = "/api/auth*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/backup*"
  to = "/.netlify/functions/backup"
  status = 200

[[redirects]]
  from = "/api/users*"
  to = "/.netlify/functions/users"
  status = 200
