[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/jobs*"
  to = "/.netlify/functions/jobs"
  status = 200

[[redirects]]
  from = "/api/photo*"
  to = "/.netlify/functions/photo"
  status = 200

[[redirects]]
  from = "/api/report*"
  to = "/.netlify/functions/report"
  status = 200
